"""Mitigation policy: generation from measured effectiveness + runtime application.

The policy is DERIVED (plan/phases/phase-3 §3.3), never hand-tuned: for each subtype
pick the chain with the best mean ΔWER across levels, but only if it improves WER
≥ 3% relative in **both** languages, stays within the latency budget, and does not
worsen KER. Otherwise `none`. `configs/mitigation_policy.yaml` is generated — never
hand-edit it (CLAUDE.md hard rule 3).
"""

from __future__ import annotations

import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml

from ars.contracts import PreprocessReport
from ars.preprocess.denoisers import NoneDenoiser, get_denoiser

SR = 16000
LATENCY_BUDGET_MS = 400.0  # mitigation chain budget (02 §7)
MIN_REL_IMPROVEMENT = 0.03
_KER_EPS = 1e-6


def _mean(series: pd.Series) -> float:
    vals = series.dropna()
    return float(vals.mean()) if len(vals) else float("nan")


def generate_policy(
    df: pd.DataFrame,
    latency_budget_ms: float = LATENCY_BUDGET_MS,
    min_rel_improvement: float = MIN_REL_IMPROVEMENT,
) -> dict[str, Any]:
    """Effectiveness table -> {subtype: chain}. Columns: subtype, level, lang, chain, wer,
    ker, latency_ms. A chain is chosen only if it helps WER in BOTH langs, respects the
    latency budget, and does not worsen KER."""
    langs = sorted(df["lang"].unique())
    chains = [c for c in df["chain"].unique() if c != "none"]
    policy: dict[str, str] = {}

    for subtype in sorted(df["subtype"].unique()):
        sdf = df[df["subtype"] == subtype]
        best_chain, best_score = "none", -np.inf
        for chain in chains:
            per_lang_rel = []
            ok = True
            for lang in langs:
                none_rows = sdf[(sdf["lang"] == lang) & (sdf["chain"] == "none")]
                chain_rows = sdf[(sdf["lang"] == lang) & (sdf["chain"] == chain)]
                if none_rows.empty or chain_rows.empty:
                    ok = False
                    break
                none_wer, chain_wer = _mean(none_rows["wer"]), _mean(chain_rows["wer"])
                rel = (none_wer - chain_wer) / max(none_wer, 1e-6)
                none_ker, chain_ker = _mean(none_rows["ker"]), _mean(chain_rows["ker"])
                lat = _mean(chain_rows["latency_ms"])
                worsens_ker = (
                    not np.isnan(chain_ker)
                    and not np.isnan(none_ker)
                    and chain_ker > none_ker + _KER_EPS
                )
                if (
                    rel < min_rel_improvement
                    or worsens_ker
                    or (not np.isnan(lat) and lat > latency_budget_ms)
                ):
                    ok = False
                    break
                per_lang_rel.append(rel)
            if ok:
                score = min(per_lang_rel)  # must help the worst language too
                if score > best_score:
                    best_chain, best_score = chain, score
        policy[subtype] = best_chain
    return policy


def write_policy_yaml(policy: dict[str, str], path: str | Path, meta: dict | None = None) -> None:
    header = {
        "generated_by": "ars.preprocess.gen_policy",
        "generated_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "latency_budget_ms": LATENCY_BUDGET_MS,
        "min_rel_improvement": MIN_REL_IMPROVEMENT,
        **(meta or {}),
    }
    doc = {"_meta": header, "policy": dict(sorted(policy.items()))}
    Path(path).write_text(
        "# GENERATED by ars.preprocess.gen_policy — do not hand-edit (CLAUDE.md rule 3).\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def load_policy(path: str | Path) -> dict[str, str]:
    doc = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    return doc["policy"]


class PolicyPreprocessor:
    """Runtime AXIS 1: classify -> policy lookup -> chain. Honors the Preprocessor seam.

    mode: off (no classify, identity) | log_only (classify + log, apply none) |
    active (classify + apply the mapped chain). log_only is the production-safe default.
    """

    def __init__(self, classifier, policy: dict[str, str], mode: str = "log_only") -> None:
        self.classifier = classifier
        self.policy = policy or {}
        self.mode = mode
        self._cache: dict[str, Any] = {"none": NoneDenoiser()}

    def _denoiser(self, chain_id: str):
        if chain_id not in self._cache:
            self._cache[chain_id] = get_denoiser(chain_id)
        return self._cache[chain_id]

    def process(self, audio: np.ndarray, sr: int = SR) -> tuple[np.ndarray, PreprocessReport]:
        t0 = time.perf_counter()
        audio = np.ascontiguousarray(audio, dtype=np.float32)
        if self.mode == "off" or self.classifier is None:
            return audio, PreprocessReport(latency_ms=(time.perf_counter() - t0) * 1000.0)

        pred = self.classifier.predict(audio, sr)
        chain_id = self.policy.get(pred.subtype, "none") if pred.subtype else "none"

        applied: list[str] = []
        out = audio
        if self.mode == "active" and chain_id != "none":
            out = self._denoiser(chain_id).process(audio, sr)
            applied = [chain_id]
        report = PreprocessReport(
            noise_pred=pred.subtype,
            noise_confidence=pred.confidence,
            chain_applied=applied,
            latency_ms=(time.perf_counter() - t0) * 1000.0,
        )
        return out, report
